/*
 *	This program is the CONFIDENTIAL and PROPRIETARY property 
 *	of Tomasello Software LLC. Any unauthorized use, reproduction or
 *	transfer of this computer program is strictly prohibited.
 *
 *      Copyright (c) 2004 Tomasello Software LLC.
 *	This is an unpublished work, and is subject to limited distribution and
 *	restricted disclosure only. ALL RIGHTS RESERVED.
 *
 *			RESTRICTED RIGHTS LEGEND
 *	Use, duplication, or disclosure by the Government is subject to
 *	restrictions set forth in subparagraph (c)(1)(ii) of the Rights in
 * 	Technical Data and Computer Software clause at DFARS 252.227-7013.
 *
 *	Angel Island UO Shard	Version 1.0
 *			Release A
 *			March 25, 2004
 */
/*   changelog.
 *   08/03/06,Rhiannon
 *		Initial creation
 *
 *
 */
/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DisplayCaseSmallSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DisplayCaseSmallSouthAddonDeed();
			}
		}

		[Constructable]
		public DisplayCaseSmallSouthAddon()
		{
			AddComponent(new AddonComponent(2840), 1, 1, 0);
			AddComponent(new AddonComponent(2840), 1, 1, 5);
			AddComponent(new AddonComponent(2833), 1, 1, 2);
			AddComponent(new AddonComponent(2720), 0, 1, 5);
			AddComponent(new AddonComponent(2837), 0, 1, 2);
			AddComponent(new AddonComponent(2725), -1, 1, 0);
			AddComponent(new AddonComponent(2725), -1, 1, 5);
			AddComponent(new AddonComponent(2834), -1, 1, 2);
			AddComponent(new AddonComponent(2723), -1, 0, 0);
			AddComponent(new AddonComponent(2723), -1, 0, 5);
			AddComponent(new AddonComponent(2832), -1, 0, 2);
			AddComponent(new AddonComponent(2722), 0, 0, 5);
			AddComponent(new AddonComponent(2839), 0, 0, 2);
			AddComponent(new AddonComponent(2724), 1, 0, 0);
			AddComponent(new AddonComponent(2724), 1, 0, 5);
			AddComponent(new AddonComponent(2835), 1, 0, 2);
			AddonComponent ac = null;
			ac = new AddonComponent(2723);
			AddComponent(ac, -1, 0, 0);
			ac = new AddonComponent(2722);
			AddComponent(ac, 0, 0, 5);
			ac = new AddonComponent(2723);
			AddComponent(ac, -1, 0, 5);
			ac = new AddonComponent(2839);
			AddComponent(ac, 0, 0, 2);
			ac = new AddonComponent(2832);
			AddComponent(ac, -1, 0, 2);

		}

		public DisplayCaseSmallSouthAddon(Serial serial)
			: base(serial)
		{
		}

		public override void Serialize(GenericWriter writer)
		{
			base.Serialize(writer);
			writer.Write(0); // Version
		}

		public override void Deserialize(GenericReader reader)
		{
			base.Deserialize(reader);
			int version = reader.ReadInt();
		}
	}

	public class DisplayCaseSmallSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DisplayCaseSmallSouthAddon();
			}
		}

		[Constructable]
		public DisplayCaseSmallSouthAddonDeed()
		{
			Name = "small display case (south)";
		}

		public DisplayCaseSmallSouthAddonDeed(Serial serial)
			: base(serial)
		{
		}

		public override void Serialize(GenericWriter writer)
		{
			base.Serialize(writer);
			writer.Write(0); // Version
		}

		public override void Deserialize(GenericReader reader)
		{
			base.Deserialize(reader);
			int version = reader.ReadInt();
		}
	}
}