/*
 *	This program is the CONFIDENTIAL and PROPRIETARY property 
 *	of Tomasello Software LLC. Any unauthorized use, reproduction or
 *	transfer of this computer program is strictly prohibited.
 *
 *      Copyright (c) 2004 Tomasello Software LLC.
 *	This is an unpublished work, and is subject to limited distribution and
 *	restricted disclosure only. ALL RIGHTS RESERVED.
 *
 *			RESTRICTED RIGHTS LEGEND
 *	Use, duplication, or disclosure by the Government is subject to
 *	restrictions set forth in subparagraph (c)(1)(ii) of the Rights in
 * 	Technical Data and Computer Software clause at DFARS 252.227-7013.
 *
 *	Angel Island UO Shard	Version 1.0
 *			Release A
 *			March 25, 2004
 */
/*   changelog.
 *   08/03/06,Rhiannon
 *		Initial creation
 *
 *
 */
/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DisplayCaseNarrowEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DisplayCaseNarrowEastAddonDeed();
			}
		}

		[Constructable]
		public DisplayCaseNarrowEastAddon()
		{
			AddComponent(new AddonComponent(2840), 1, 2, 6);
			AddComponent(new AddonComponent(2833), 1, 2, 3);
			AddComponent(new AddonComponent(2840), 1, 2, 0);
			AddComponent(new AddonComponent(2721), 0, 0, 6);
			AddComponent(new AddonComponent(2838), 0, 0, 3);
			AddComponent(new AddonComponent(2723), 0, -1, 6);
			AddComponent(new AddonComponent(2832), 0, -1, 3);
			AddComponent(new AddonComponent(2723), 0, -1, 0);
			AddComponent(new AddonComponent(2719), 1, 1, 6);
			AddComponent(new AddonComponent(2836), 1, 1, 3);
			AddComponent(new AddonComponent(2721), 0, 1, 6);
			AddComponent(new AddonComponent(2838), 0, 1, 3);
			AddComponent(new AddonComponent(2724), 1, -1, 6);
			AddComponent(new AddonComponent(2835), 1, -1, 3);
			AddComponent(new AddonComponent(2724), 1, -1, 0);
			AddComponent(new AddonComponent(2836), 1, 0, 3);
			AddComponent(new AddonComponent(2719), 1, 0, 6);
			AddComponent(new AddonComponent(2725), 0, 2, 6);
			AddComponent(new AddonComponent(2834), 0, 2, 3);
			AddComponent(new AddonComponent(2725), 0, 2, 0);
			AddonComponent ac = null;
			ac = new AddonComponent(2723);
			AddComponent(ac, 0, -1, 6);
			ac = new AddonComponent(2721);
			AddComponent(ac, 0, 0, 6);
			ac = new AddonComponent(2721);
			AddComponent(ac, 0, 1, 6);
			ac = new AddonComponent(2838);
			AddComponent(ac, 0, 0, 3);
			ac = new AddonComponent(2832);
			AddComponent(ac, 0, -1, 3);
			ac = new AddonComponent(2838);
			AddComponent(ac, 0, 1, 3);
			ac = new AddonComponent(2723);
			AddComponent(ac, 0, -1, 0);

		}

		public DisplayCaseNarrowEastAddon(Serial serial)
			: base(serial)
		{
		}

		public override void Serialize(GenericWriter writer)
		{
			base.Serialize(writer);
			writer.Write(0); // Version
		}

		public override void Deserialize(GenericReader reader)
		{
			base.Deserialize(reader);
			int version = reader.ReadInt();
		}
	}

	public class DisplayCaseNarrowEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DisplayCaseNarrowEastAddon();
			}
		}

		[Constructable]
		public DisplayCaseNarrowEastAddonDeed()
		{
			Name = "narrow display case (east)";
		}

		public DisplayCaseNarrowEastAddonDeed(Serial serial)
			: base(serial)
		{
		}

		public override void Serialize(GenericWriter writer)
		{
			base.Serialize(writer);
			writer.Write(0); // Version
		}

		public override void Deserialize(GenericReader reader)
		{
			base.Deserialize(reader);
			int version = reader.ReadInt();
		}
	}
}